/**
 * This file is auto-generated by the vite-plugin-topic-titles-manifest plugin.
 * Do not edit manually. Run `bun run build` or `bun run dev` to regenerate.
 *
 * Maps topic slugs to their actual titles extracted from markdown files.
 */
export const TOPIC_TITLES: Record<string, string> = {
  'adding-objects': 'Adding Objects',
  'ai-features': 'AI Create & Edit',
  'audio-chaining': 'Audio Chaining',
  'audio-reactivity': 'Audio Reactivity',
  'canvas-interaction': 'Canvas Interaction Control',
  'connecting-objects': 'Connecting Objects',
  'connection-rules': 'Connection Rules',
  'getting-started': 'Getting Started',
  'hot-cold-inlets': 'Hot and Cold Inlets',
  'in-app-help': 'Help',
  'javascript-runner': 'Patchies JavaScript Runner',
  'keyboard-shortcuts': 'Keyboard Shortcuts',
  'manage-files': 'Files',
  'manage-packs': 'Packs',
  'manage-presets': 'Presets',
  'manage-saves': 'Saves',
  'message-passing': 'Message Passing',
  'modifying-objects': 'Modifying Objects',
  'offline-usage': 'Offline Usage',
  'rendering-pipeline': 'Rendering Pipeline',
  'sharing-links': 'Sharing Links',
  'supporting-open-source': 'Supporting Open Source',
  'video-chaining': 'Video Chaining'
};
