import { fftInstructions } from './shared-fft';
import { messagingInstructions } from './shared-messaging';
import { jsRunnerInstructions } from './shared-jsrunner';

export const hydraPrompt = `## hydra Object Instructions

Live coding video synthesis with chainable Hydra functions.

${jsRunnerInstructions}

**Hydra-specific methods:**
- setVideoCount(inlets, outlets) - Configure video ports (default 1, 1)
- src(s0), src(s1), etc. - Access video inputs from setVideoCount
- out(o0), out(o1), etc. - Set outputs from setVideoCount
- Standard Hydra: .blend(), .add(), .mult(), .diff(), .kaleid(), etc.

**Hydra-specific gotchas:**
- Hydra has its own render loop - use arrow functions for dynamic values instead of requestAnimationFrame

${messagingInstructions}

${fftInstructions}

**Handle IDs (Auto-generated by setVideoCount/setPortCount):**
- setVideoCount(2, 1): "video-in-0", "video-in-1", "video-out-0"
- setPortCount(1, 1): "message-in-0", "message-out-0"

Example - Video mixer:
\`\`\`json
{
  "type": "hydra",
  "data": {
    "code": "setVideoCount(2, 1); src(s0).blend(src(s1), 0.5).out(o0)"
  }
}
\`\`\`

Example - Audio-reactive:
\`\`\`json
{
  "type": "hydra",
  "data": {
    "code": "src(s0).scale(() => 1 + fft().a[10] * 0.5).kaleid().out(o0)"
  }
}
\`\`\``;
