import { fftInstructions } from './shared-fft';
import { messagingInstructions } from './shared-messaging';
import { jsRunnerInstructions } from './shared-jsrunner';

export const threePrompt = `## three object instructions

Three.js 3D graphics environment running in a Web Worker (offscreen rendering). Use for GPU-accelerated 3D scenes that chain with other video nodes.

${jsRunnerInstructions}

**Three-specific globals:**
- THREE: Full Three.js library namespace
- renderer: WebGLRenderer instance
- width, height: Canvas dimensions
- mouse: {x, y} coordinates

**Three-specific methods:**
- setVideoCount(inlets, outlets) - Configure video inlets/outlets (default 1, 1)
- getTexture(index) - Get Three.js Texture from video inlet (0-based index)
- noDrag() - Disable node dragging
- noOutput() - Hide video output port
- setHidePorts(bool) - Toggle port visibility

**Three-specific gotchas:**
- Use draw(time) function for render loop instead of requestAnimationFrame
- Runs in web worker - no direct DOM access

${messagingInstructions}

${fftInstructions}

**Handle IDs (Auto-generated by setVideoCount/setPortCount):**
- setVideoCount(2, 1): "video-in-0", "video-in-1", "video-out-0"
- setPortCount(1, 1): "message-in-0", "message-out-0"

**Render Pattern:**
Define a \`draw(time)\` function that will be called every frame:
\`\`\`js
function draw(time) {
  // Update scene
  renderer.render(scene, camera)
}
\`\`\`

Example - Basic rotating cube:
\`\`\`json
{
  "type": "three",
  "data": {
    "code": "const { Scene, PerspectiveCamera, BoxGeometry, Mesh, MeshNormalMaterial } = THREE\\n\\nconst scene = new Scene()\\nconst camera = new PerspectiveCamera(75, width / height, 0.1, 1000)\\ncamera.position.z = 2\\n\\nconst geometry = new BoxGeometry(1, 1, 1)\\nconst material = new MeshNormalMaterial()\\nconst cube = new Mesh(geometry, material)\\nscene.add(cube)\\n\\nfunction draw(t) {\\n  cube.rotation.x += 0.01\\n  cube.rotation.y += 0.01\\n  renderer.render(scene, camera)\\n}"
  }
}
\`\`\`

Example - Video texture on 3D shape:
\`\`\`json
{
  "type": "three",
  "data": {
    "code": "const { Scene, PerspectiveCamera, TorusKnotGeometry, Mesh, MeshBasicMaterial } = THREE\\n\\nsetVideoCount(1, 1)\\n\\nconst scene = new Scene()\\nconst camera = new PerspectiveCamera(75, width / height, 0.1, 1000)\\ncamera.position.z = 2.5\\n\\nconst geometry = new TorusKnotGeometry(0.8, 0.25, 150, 20)\\nconst material = new MeshBasicMaterial({ color: 0xffffff })\\nconst shape = new Mesh(geometry, material)\\nscene.add(shape)\\n\\nfunction draw(t) {\\n  const tex = getTexture(0)\\n  if (tex) {\\n    material.map = tex\\n    material.needsUpdate = true\\n  }\\n  shape.rotation.x = t * 0.0005\\n  shape.rotation.y = t * 0.0008\\n  renderer.render(scene, camera)\\n}"
  }
}
\`\`\``;
