export const tonePrompt = `## tone~ Object Instructions

CRITICAL RULES FOR TONE.JS:
1. NEVER use .toDestination() - always use .connect(outputNode)
2. ALWAYS call setTitle() and setPortCount() at the start
3. To connect audio inlet: inputNode.connect(node.input.input) (mind the double .input)
4. ALWAYS return cleanup object: { cleanup: () => node.dispose() }
5. Use ABSOLUTE TIME VALUES in seconds for duration (NOT musical notation like '8n', '16n'):
   - Synths with notes: synth.triggerAttackRelease('C4', 0.25)  // 0.25 seconds
   - NoiseSynth: noise.triggerAttackRelease(0.1)  // 0.1 seconds duration
   - MetalSynth: metal.triggerAttackRelease(0.05)  // 0.05 seconds
   - MembraneSynth: kick.triggerAttackRelease('C2', 0.5)  // 0.5 seconds
6. Common duration values: 0.05 (short), 0.1 (snappy), 0.25 (quarter note), 0.5 (half note)
7. Do NOT use musical notation ('8n', '16n') unless you start Tone.Transport

HANDLE IDS (Auto-generated by SimpleDspLayout):
- Audio inlet (always present): "audio-in" (index 0 in total inlet count)
- Audio outlet (always present): "audio-out" (index 0 in total outlet count)
- Message inlets (when setPortCount(n) where n > 0): "message-in-0", "message-in-1", etc.
  * CRITICAL: Even with setPortCount(1), use "message-in-0" (NOT "message-in")
  * With setPortCount(2), use "message-in-0", "message-in-1"
- Message outlets (when setPortCount(n, m) where m > 0): "message-out-0", "message-out-1", etc.
  * CRITICAL: Even with setPortCount(1, 1), use "message-out-0" (NOT "message-out")

Available in context:
- Tone: the Tone.js library
- inputNode: GainNode for receiving audio input
- outputNode: GainNode for sending audio output (USE THIS, not toDestination!)
- setTitle(name): set the node title
- setPortCount(inlets, outlets): set message port counts
- recv(callback): receive messages
- send(data): send messages

Example - Polyphonic Synth:
\`\`\`json
{
  "type": "tone~",
  "data": {
    "code": "setPortCount(1)\\nsetTitle('synth~')\\n\\nconst synth = new Tone.PolySynth(Tone.Synth, {\\n  oscillator: { type: \\"fatsine\\" },\\n  envelope: { attack: 0.01, release: 0.9 }\\n}).connect(outputNode);\\n\\nrecv(m => {\\n  const now = Tone.now();\\n  if (m.type === 'noteOn') {\\n    const freq = Tone.Frequency(m.note, \\"midi\\").toNote();\\n    synth.triggerAttack(freq, now, m.velocity / 127);\\n  } else if (m.type === 'noteOff') {\\n    const freq = Tone.Frequency(m.note, \\"midi\\").toNote();\\n    synth.triggerRelease(freq, now);\\n  }\\n});\\n\\nreturn { cleanup: () => synth.dispose() };"
  }
}
\`\`\`

Example - Lowpass Filter:
\`\`\`json
{
  "type": "tone~",
  "data": {
    "code": "setPortCount(1)\\nsetTitle('lowpass~')\\n\\nconst filter = new Tone.Filter(5000, \\"lowpass\\")\\ninputNode.connect(filter.input.input)\\nfilter.connect(outputNode)\\n\\nrecv(m => {\\n  filter.frequency.value = m;\\n})\\n\\nreturn { cleanup: () => filter.dispose() }"
  }
}
\`\`\`

Example - Button triggering 808 Kick drum:
\`\`\`json
{
  "nodes": [
    { "type": "button", "data": { "text": "Kick" }, "position": { "x": 0, "y": 0 } },
    { 
      "type": "tone~", 
      "data": { 
        "code": "setPortCount(1);\\nsetTitle('808 Kick');\\n\\nconst kick = new Tone.MembraneSynth({ pitchDecay: 0.05, octaves: 10, oscillator: { type: 'sine' }, envelope: { attack: 0.001, decay: 0.4, sustain: 0.01, release: 0.8 } }).connect(outputNode);\\n\\nrecv(m => { if (m && m.type === 'bang') kick.triggerAttackRelease('C2', 0.5); });\\n\\nreturn { cleanup: () => kick.dispose() };" 
      },
      "position": { "x": 0, "y": 150 }
    },
    { "type": "object", "data": { "expr": "dac~", "name": "dac~", "params": [] }, "position": { "x": 0, "y": 300 } }
  ],
  "edges": [
    { "source": 0, "target": 1, "sourceHandle": "message-out", "targetHandle": "message-in-0" },
    { "source": 1, "target": 2, "sourceHandle": "audio-out", "targetHandle": "audio-in-0" }
  ]
}
\`\`\`
Note: button → tone~ uses targetHandle: "message-in-0" (NOT "message-in")

Example - 808 Snare (combining noise and tone):
\`\`\`json
{
  "type": "tone~",
  "data": {
    "code": "setPortCount(1);\\nsetTitle('808 Snare');\\n\\nconst noise = new Tone.NoiseSynth({ noise: { type: 'white' }, envelope: { attack: 0.001, decay: 0.1, sustain: 0, release: 0.05 } }).connect(outputNode);\\n\\nconst body = new Tone.MembraneSynth({ pitchDecay: 0.01, octaves: 5, envelope: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.1 }, oscillator: { type: 'triangle' } }).connect(outputNode);\\n\\nrecv(m => { if (m && m.type === 'bang') { noise.triggerAttackRelease(0.1); body.triggerAttackRelease('A3', 0.125); } });\\n\\nreturn { cleanup: () => { noise.dispose(); body.dispose(); } };"
  }
}
\`\`\`
CRITICAL: Use absolute time in seconds (0.1, 0.5) NOT musical notation ('16n', '8n')`;
