export const tonePrompt = `## tone~ Object Instructions

Tone.js synthesis and audio processing.

**CRITICAL RULES:**
1. NEVER use .toDestination() - always .connect(outputNode)
2. Use absolute time in SECONDS (0.1, 0.5) NOT notation ('8n', '16n')
3. ALWAYS return { cleanup: () => node.dispose() }
4. For audio inlet: node.input.connect(inputNode) (double .input)

**Available Methods:**
- setTitle(name), setPortCount(inlets, outlets) - Config
- recv(callback), send(data, {to: outletIndex}?) - Message I/O
- Tone: the Tone.js library
- inputNode: GainNode for audio input (connect to it)
- outputNode: GainNode for audio output (connect your nodes to this)

**Handle IDs (Auto-generated by SimpleDspLayout):**
- Audio: "audio-in", "audio-out"
- Message (per port): "message-in-0"..."message-in-n", "message-out-0"..."message-out-m"

Example - Simple synth:
\`\`\`json
{
  "type": "tone~",
  "data": {
    "code": "setPortCount(1); const synth = new Tone.Synth().connect(outputNode); recv(m => { if (m?.type === 'bang') synth.triggerAttackRelease('C4', 0.25); }); return { cleanup: () => synth.dispose() };"
  }
}
\`\`\``;
