// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Comment = 1,
	Program = 2,
	StringDefinition = 3,
	Identifier = 4,
	String = 5,
	ValueDefinition = 6,
	Value = 7,
	InstructionExpression = 8,
	Instruction = 9,
	LabelDefinition = 10;
