/**
 * This file is auto-generated by the vite-plugin-help-patches-manifest plugin.
 * Do not edit manually. Run `bun run build` or `bun run dev` to regenerate.
 *
 * Lists all object types that have help patches available in /static/help-patches/
 */
export const HELP_PATCHES_AVAILABLE: ReadonlySet<string> = new Set([]);
