import { readdirSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import type { Plugin } from 'vite';

const HELP_PATCHES_DIR = 'static/help-patches';
const MANIFEST_PATH = 'src/lib/objects/help-patches-manifest.ts';

function generateManifest(root: string): void {
  const helpPatchesDir = join(root, HELP_PATCHES_DIR);
  const manifestPath = join(root, MANIFEST_PATH);

  let objectTypes: string[] = [];

  if (existsSync(helpPatchesDir)) {
    objectTypes = readdirSync(helpPatchesDir)
      .filter((file) => file.endsWith('.json'))
      .map((file) => file.replace(/\.json$/, ''))
      .sort();
  }

  const content = `/**
 * This file is auto-generated by the vite-plugin-help-patches-manifest plugin.
 * Do not edit manually. Run \`bun run build\` or \`bun run dev\` to regenerate.
 *
 * Lists all object types that have help patches available in /static/help-patches/
 */
export const HELP_PATCHES_AVAILABLE: ReadonlySet<string> = new Set([
${objectTypes.map((t) => `  '${t}',`).join('\n')}
]);
`;

  writeFileSync(manifestPath, content);

  console.log(`[help-patches-manifest] Generated manifest with ${objectTypes.length} entries`);
}

/**
 * Vite plugin that generates a manifest of available help patches at build time.
 * This eliminates the need for runtime HEAD requests that cause 404 errors.
 */
export function helpPatchesManifest(): Plugin {
  let root: string;

  return {
    name: 'help-patches-manifest',

    configResolved(config) {
      root = config.root;
    },

    buildStart() {
      generateManifest(root);
    },

    configureServer(server) {
      // Watch for changes in help-patches directory during dev
      server.watcher.add(join(root, HELP_PATCHES_DIR));

      server.watcher.on('add', (path) => {
        if (path.includes(HELP_PATCHES_DIR) && path.endsWith('.json')) {
          generateManifest(root);
        }
      });

      server.watcher.on('unlink', (path) => {
        if (path.includes(HELP_PATCHES_DIR) && path.endsWith('.json')) {
          generateManifest(root);
        }
      });
    }
  };
}
