import { readdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import type { Plugin } from 'vite';

const TOPICS_DIR = 'static/content/topics';
const MANIFEST_PATH = 'src/lib/docs/topic-titles-manifest.ts';

/**
 * Extract title from markdown content (first # heading)
 */
function extractTitle(markdown: string): string | null {
  const match = markdown.match(/^#\s+(.+)$/m);
  return match ? match[1].trim() : null;
}

function generateManifest(root: string): void {
  const topicsDir = join(root, TOPICS_DIR);
  const manifestPath = join(root, MANIFEST_PATH);

  const titles: Record<string, string> = {};

  if (existsSync(topicsDir)) {
    const files = readdirSync(topicsDir).filter((file) => file.endsWith('.md'));

    for (const file of files) {
      const slug = file.replace(/\.md$/, '');
      const content = readFileSync(join(topicsDir, file), 'utf-8');
      const title = extractTitle(content);

      if (title) {
        titles[slug] = title;
      }
    }
  }

  const sortedEntries = Object.entries(titles).sort(([a], [b]) => a.localeCompare(b));

  const content = `/**
 * This file is auto-generated by the vite-plugin-topic-titles-manifest plugin.
 * Do not edit manually. Run \`bun run build\` or \`bun run dev\` to regenerate.
 *
 * Maps topic slugs to their actual titles extracted from markdown files.
 */
export const TOPIC_TITLES: Record<string, string> = {
${sortedEntries.map(([slug, title], i) => `  '${slug}': '${title.replace(/'/g, "\\'")}'${i < sortedEntries.length - 1 ? ',' : ''}`).join('\n')}
};
`;

  writeFileSync(manifestPath, content);

  console.log(`[topic-titles-manifest] Generated manifest with ${sortedEntries.length} entries`);
}

/**
 * Vite plugin that generates a manifest of topic titles at build time.
 * This allows using actual markdown titles instead of slug-derived titles.
 */
export function topicTitlesManifest(): Plugin {
  let root: string;

  return {
    name: 'topic-titles-manifest',

    configResolved(config) {
      root = config.root;
    },

    buildStart() {
      generateManifest(root);
    },

    configureServer(server) {
      // Watch for changes in topics directory during dev
      server.watcher.add(join(root, TOPICS_DIR));

      server.watcher.on('add', (path) => {
        if (path.includes(TOPICS_DIR) && path.endsWith('.md')) {
          generateManifest(root);
        }
      });

      server.watcher.on('change', (path) => {
        if (path.includes(TOPICS_DIR) && path.endsWith('.md')) {
          generateManifest(root);
        }
      });

      server.watcher.on('unlink', (path) => {
        if (path.includes(TOPICS_DIR) && path.endsWith('.md')) {
          generateManifest(root);
        }
      });
    }
  };
}
